routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\ScheduleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/user/{user}/edit', [UserController::class, 'edit'])->name('user.edit');

Route::patch('/user/{user}', [UserController::class, 'update'])->name('user.update');

Route::resource('doctor', DoctorController::class);

Route::resource('patients', PatientController::class);

Route::resource('schedules', ScheduleController::class);

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card text-center">
                <div class="card-header">
                    {{ __('Dashboard') }}
                </div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    @if (!empty($doctorExists))
                        <a href="{{ route('doctor.index') }}" title="Meu perfil"><i class="material-icons">person</i></a>
                    @else
                        <p class="card-text"> {{ __('Logado com sucesso!') }}</p>
                    @endif

                    @if(empty($doctorExists))
                        <a href="/doctor/create" class="btn btn-primary">Meu Cadastro</a>
                    @else
                        <ul style="list-style: none;text-align: left;">
                            <li style="margin-bottom:15px;">
                                <a href="{{ route('patients.index') }}" title="Pacientes"><i class="material-icons">group</i></a>
                            </li>

                            @if(!empty($patientExists))
                                <li>
                                    <a href="{{ route('schedules.index') }}" title="Agendamentos"><i class="material-icons">schedule</i></a>
                                </li>
                            @endif
                        </ul>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection